---
book_repo: pivotal-cf/docs-book-nist
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-nist
  directory: nist
  subnav_template: nist-subnav.erb
  product_info:
    use_local_header: false
    search_placeholder: Search NIST Controls and PCF
    local_header_title: NIST Controls